var config = require('./config.json');

var W3CWebSocket = require('websocket').w3cwebsocket;

// test token generated by jwt.io
/*
HEADER:ALGORITHM & TOKEN TYPE
{
  "alg": "HS256",
  "typ": "JWT"
}

PAYLOAD:DATA
{
  "sub": "1",
  "username": "danial",
  "iat": 1516239022
}

VERIFY SIGNATURE
HMACSHA256(
  base64UrlEncode(header) + "." + 
  base64UrlEncode(payload),
  s3cu73-c0$3
)
*/
const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJkYW5pYWwiLCJpYXQiOjE1MTYyMzkwMjJ9.6vrqV-_brni7bxmYAIDKPkU3k6Ymsj5rmD3hnGrF7q4"

var client = new W3CWebSocket('ws://'+config.webSocketUrl+config.apiVersionPrefix+'/ws' + '?token=' + token);

client.onerror = function() {
    console.log('Connection Error');
};

client.onopen = function() {
    console.log('WebSocket Client Connected');

    function openConnection() {
        if (client.readyState === client.OPEN) {
            console.log("Sent: connection opened");
        }
    }
    openConnection()
};

client.onclose = function() {
    console.log('echo-protocol Client Closed');
};

client.onmessage = function(e) {
    if (typeof e.data === 'string') {
        console.log("Received: '" + e.data + "'");
    }
};
